[package]
name = "anchor-attribute-event"
version.workspace = true
repository.workspace = true
license.workspace = true
description = "Anchor attribute macro for defining an event"
rust-version = "1.60"
edition.workspace = true

[lib]
proc-macro = true

[features]
anchor-debug = ["anchor-syn/anchor-debug"]
event-cpi = ["anchor-syn/event-cpi"]
idl-build = ["anchor-syn/idl-build"]

[dependencies]
anchor-syn = { path = "../../syn", features = ["hash"] }
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["full"] }
