[package]
name = "anchor-derive-space"
version.workspace = true
repository.workspace = true
license.workspace = true
description = "Anchor Derive macro to automatically calculate the size of a structure or an enum"
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["extra-traits"] }
