[package]
name = "anchor-derive-accounts"
version.workspace = true
repository.workspace = true
license.workspace = true
description = "Anchor Derive macro for accounts"
edition.workspace = true

[lib]
proc-macro = true

[features]
allow-missing-optionals = ["anchor-syn/allow-missing-optionals"]
anchor-debug = ["anchor-syn/anchor-debug"]
idl-build = ["anchor-syn/idl-build"]
init-if-needed = ["anchor-syn/init-if-needed"]

[dependencies]
anchor-syn = { path = "../../syn", version = "0.32.1" }
quote = "1"
syn = { version = "1", features = ["full"] }
