[package]
name = "anchor-derive-serde"
version.workspace = true
repository.workspace = true
license.workspace = true
description = "Anchor Derive macro for serialization and deserialization"
edition.workspace = true

[lib]
proc-macro = true

[features]
idl-build = ["anchor-syn/idl-build"]
lazy-account = []

[dependencies]
anchor-syn = { path = "../../syn" }
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["full"] }
