[package]
name = "anchor-attribute-program"
version.workspace = true
repository.workspace = true
license.workspace = true
description = "Anchor attribute macro for defining a program"
edition.workspace = true

[lib]
proc-macro = true

[features]
anchor-debug = ["anchor-syn/anchor-debug"]
idl-build = ["anchor-syn/idl-build"]

[dependencies]
anchor-lang-idl = { path = "../../../idl", version = "0.1.2", features = ["convert"] }
anchor-syn = { path = "../../syn", version = "0.32.1" }
anyhow = "1"
heck = "0.3"
proc-macro2 = "1"
quote = "1"
serde_json = "1"
syn = { version = "1", features = ["full"] }
